[tool.poetry]
name = "flint"
version = "1.0.0"
description = "Enterprise Cloud Automation & Continuous Delivery Platform"
authors = ["Kusuma Podili <kusuma.podili@enterprise.io>"]

[tool.poetry.dependencies]
python = "^3.10"
cryptography = ">=41.0.0"
pyyaml = ">=6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
